sudo: required
services: 
  - docker

before_install:
  - docker build -t mducic/docker-react -f Dockerfile.dev .

script:
  - docker run mducic/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "mdocker"
  env: "Mdocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-788787630748"
  bucket_path: "mdocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"