version: "3"
services:
  react-app:
    # Custom Dockerfile name
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # Volume mounting system
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]